### PR TITLE
New STL Files

### PR DESCRIPTION
**Pull request by paul63**
A new done frame which is lighter and has a holder for an on/off switch.
Propeller guard STL.

### CODE REVIEW

**Comment by anish-natekar** [comment]
I have merged your commit. Sorry for the late response, I really appreciate your contribution and will surely try your prop guards.

**Comment by paul63** [comment]
Hi,Great. Thanks for letting me know. I will set up a project for the joystick controller and send the details to you once ready.Best wishesPaulSent from my iPadOn 4 Sep 2023, at 17:10, Anish ***@***.***> wrote:﻿
I have merged your commit. Sorry for the late response, I really appreciate your contribution and will surely try your prop guards.

**Comment by paul63** [comment]
Hi Anish,

I have now published my joystick controller on Hackster.io.

https://www.hackster.io/paulsb/drone-joystick-controller-25e036

Have a look and, if you think others may be interested, can you add a link
to your documentation.

Best wishes

Paul

**Comment by anish-natekar** [comment]
Sure, i'll make the changes to my docs and update it by this weekend.
This controller looks great I will try to build, and test it soon. I like that you have added a charging port for the Lipo.
I might build a simpler one without a display. In the future I want to try adding a FPV AIO camera to the drone that can send video to my phone so I might try adding a phone holder in the stl file of the remote.

**Comment by paul63** [comment]
Great - many thanks.

Best wishes

Paul

**Comment by anish-natekar** [comment]
Hi Paul,

I have updated the documentation - https://picow-copter-docs.readthedocs.io/en/latest/
I have mentioned your project under the Hardware section with a link to your article.

Best
Anish Natekar

**Comment by paul63** [comment]
Hi AnishMany thanks.Best wishesPaulSent from my iPadOn 9 Sep 2023, at 16:20, Anish ***@***.***> wrote:﻿
Hi Paul,
I have updated the documentation - https://picow-copter-docs.readthedocs.io/en/latest/
I have mentioned your project under the Hardware section with a link to your article.
Best
Anish Natekar

**Pull request merged**
